services:
  app:
    image: ${DOCKER_USERNAME}/chats-crm-system:${IMAGE_TAG:-latest}
    container_name: chats-crm-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${APP_PORT:-8000}:80"
    networks:
      - app-network
    volumes:
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
networks:
  app-network:
    driver: bridge
